### ISSUE TITLE
关于瀑布流

### ISSUE THREAD

**Issue by jackyon** [myronliu347/wechat-app-zhihudaily#1]
你好，请教下几个问题：
- 瀑布流是否现在只能通过点击按钮去触发？ 微信小程序还没有监听底部事件？
- html到现在还无法微信小程序编译出来？

**Comment by myronliu347** [comment]
- 小程序可以通过 [scroll-view](https://mp.weixin.qq.com/debug/wxadoc/dev/component/scroll-view.html?t=1474644087418) 组件监听滚动到底部，
- 现在还没有html解析的api， 动态创建视图的api也没有，只能编写模板。

**Comment by jackyon** [comment]
谢谢解惑。
貌似图片也没有lazyload的功能

**Comment by myronliu347** [comment]
暂时没有做，这个是可以实现的
